world_id: "demo"
robot_specification {
  robot_reference {
    object_id {
      id: "ofid_2"
      debug_hint: "panda"
    }
  }
  start_configuration {
    joints: -0.01590006405091247
    joints: -0.1720477187467986
    joints: 0.007712579019363479
    joints: -2.4054709308749014
    joints: 0.0020521649283593447
    joints: 2.2060108942032133
    joints: 0.7818871713814125
  }
}
motion_specification {
  motion_segments {
    target {
      cartesian_pose {
        moving_frame {
          id: "ofid_26"
          debug_hint: "panda/flange"
        }
        target_frame {
          id: "root"
          debug_hint: "root"
        }
        target_frame_offset {
          position {
            x: -0.12614728834129407
            y: -0.15410493531624367
            z: 0.5753443018812906
          }
          orientation {
            x: 0.7071067811865475
            y: 0.7071067811865475
          }
        }
      }
    }
    collision_settings {
    }
  }
}
motion_planner_config {
  timeout_sec {
    seconds: 20
  }
}
caller_id: "libero_bridge"
